### ISSUE TITLE
Minor Error. Amp Code

### ISSUE THREAD

**Issue by kalverra** [ginacastano/prj-rev-bwfs-dasmoto#1]
https://github.com/ginacastano/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/index.html#L5

& is a special character in HTML, check here. http://rabbit.eng.miami.edu/info/htmlchars.html

**Comment by ginacastano** [comment]
My editor turned the ampersand red when I typed it, but since it displayed in the browser, I didn't looking into it further. Now I know to check - thank you for the link!
